#server.port=8082
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#spring.application.name=movie-info-service
server:
  port: 8082
spring:
  application:
    name: movie-info-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true